### ISSUE TITLE
Comparing signed vs. unsigned integers

### ISSUE THREAD

**Issue by bayotop** [surendra060/PCAP_TCP_PARSER#3]
Location: lines no. 273, 290, 301, 337 in main.c
Description : The software performs a calculation that can produce an integer overflow or wraparound, when the logic assumes that the resulting value will always be larger than the original value.

**Comment by surendra060** [comment]
Error Identified in all the indicated lines as comparison of  **int Frame_Length** variable passed to function **int ProcessFrame(unsigned char *Frame_Data,int Frame_Length)**

To be converted to Unsigned int in definition and passing of the variable to the function during use.
@ Ramu

**Comment by ramucs108** [comment]
Code modified to close the issue of "Comparison between signed vs unsigned integer"

changed int Frame_Length to unsigned int Frame_Length in function call and definition.

and modified the following variables used during function calls:
int Frame_Protocol,FrameLength  ------>  unsigned int Frame_Protocol,FrameLength
