### ISSUE TITLE
Detection of error condition without action

### ISSUE THREAD

**Issue by bayotop** [surendra060/PCAP_TCP_PARSER#4]
Location: lines no. 9, 74, and 75 in main.c
Description: The software detects a specific error, but takes no actions to handle
the error.

**Comment by surendra060** [comment]
Line 9 , 74, 75 in main.c are not error checking condition. It seems that Line reference used by you and us is not in Sync. Please use the main.c uploaded in the repository now (not in Zip Folder ) to indicate error line / copy paste the erroneous lines.

**Comment by surendra060** [comment]
Discussed with Team Member of Reviewing Team ( Milan Patnaik) and identified the correct lines and issues.  Line No 9 is Typo, and error was observed when AFL generated input was given to the program.  Error to be recreated, analyzed and rectified /appropriately commented by Rajesh Mehta.

**Comment by Globe83Earth** [comment]
Issue raised for line 74 and 75 was observed in lines 524-539 (main.c) during re-creation of issue by giving fuzzed input using AFL.

Logical assumption of FrameLength being correct in file for all frames may not be hold for a malformed/fuzzed file.
Therefore, Escaping the current frame being processed to jump to next frame is not possible.
Hence, further parsing of the input file is discontinued and program exit gracefully (two lines 558-559 of following code added)

                                ch = 0xFF; 
				printf("\n Found corrupted Frame Length and  \n");
