### ISSUE TITLE
Unused variables and dead code

### ISSUE THREAD

**Issue by bayotop** [surendra060/PCAP_TCP_PARSER#5]
Unused variables

Location : lines no. 104, 137 in main.c
Description : The variable's value is assigned but never used, making it a dead store.

Dead code starting on line 480. ErrorFrameCounter has an value >= 3.

**Comment by surendra060** [comment]
Line 104 and 137 is  a  function definition
int Extract_Eth_header(struct ether_header  *Eth_hdr, unsigned int total_frame_len){

and 

int Extract_IPdata(struct ip *ip, int IP_header_len){

Could you please point out name of Unused variabe

**Comment by surendra060** [comment]
Discussed with Team Member of Reviwing Team ( MIlan Patnaik) and identified the correct lines.

**Comment by surendra060** [comment]
With reference to the observation found using CPPCHECK by the reviewing team
Dead code starting on line 480. ErrorFrameCounter has an value >= 3.

The program was made defensive by using the check for ErrorFrameCounter==0, in case of a large input file where potentially the ErrorFrameCount gets overflown. Therefore, it is considered to be a False positive of CPPCheck

**Comment by ramucs108** [comment]
Following functions are modified to remove the unused variable passed as argument.

1. int Extract_Eth_header(struct ether_header  *Eth_hdr, unsigned int total_frame_len) -----> int Extract_Eth_header(struct ether_header  *Eth_hdr) 

2. int Extract_IPdata(struct ip *ip, int IP_header_len)    ---->   int Extract_IPdata(struct ip *ip)

and corresponding function calls.
